# Change these first
owner: pokkocms # Your GitHub username
repo: pokko-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Pokko
    url: https://www.pokko.io
  - name: Pokko - au-syd1
    url: https://au-syd1.pokko.io
  - name: Pokko - auth service
    url: https://id.pokko.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.pokko.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /
  logoUrl: https://cdn.pokko.io/p/pokko-sharing.png
  name: System status
  introTitle: "**Pokko** uptime monitor and system status."
  introMessage: Real time system status for the entire Pokko ecosystem
  navbar:
    - title: Pokko
      href: https://www.pokko.io/
    - title: Login
      href: https://id.pokko.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
